// <auto-generated />
using System;
using MAVN.Job.TokensStatistics.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Job.TokensStatistics.MsSqlRepositories.Migrations
{
    [DbContext(typeof(TokensStatisticsContext))]
    partial class TokensStatisticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tokens_statistics")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Job.TokensStatistics.MsSqlRepositories.Entities.DailyTokensSnapshotEntity", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnName("date")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TotalBurnedTokens")
                        .IsRequired()
                        .HasColumnName("total_burned_tokens")
                        .HasColumnType("text");

                    b.Property<string>("TotalEarnedTokens")
                        .IsRequired()
                        .HasColumnName("total_earned_tokens")
                        .HasColumnType("text");

                    b.Property<string>("TotalTokens")
                        .IsRequired()
                        .HasColumnName("total_tokens")
                        .HasColumnType("text");

                    b.Property<string>("TotalTokensInCustomersWallets")
                        .IsRequired()
                        .HasColumnName("total_tokens_in_customers_wallets")
                        .HasColumnType("text");

                    b.HasKey("Date");

                    b.ToTable("daily_tokens_snapshot");
                });

            modelBuilder.Entity("MAVN.Job.TokensStatistics.MsSqlRepositories.Entities.LastKnownStatsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("LastBurnedAmount")
                        .IsRequired()
                        .HasColumnName("last_burned_amount")
                        .HasColumnType("text");

                    b.Property<string>("LastEarnedAmount")
                        .IsRequired()
                        .HasColumnName("last_earned_amount")
                        .HasColumnType("text");

                    b.Property<string>("LastTotalAmount")
                        .IsRequired()
                        .HasColumnName("last_total_amount")
                        .HasColumnType("text");

                    b.Property<string>("LastTotalTokensInCustomersWallets")
                        .IsRequired()
                        .HasColumnName("last_total_tokens_in_customers_wallets")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("last_token_total_amount");
                });
#pragma warning restore 612, 618
        }
    }
}
