// <auto-generated />
using System;
using Lykke.Job.TokensStatistics.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lykke.Job.TokensStatistics.MsSqlRepositories.Migrations
{
    [DbContext(typeof(TokensStatisticsContext))]
    partial class TokensStatisticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tokens_statistics")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Job.TokensStatistics.MsSqlRepositories.Entities.DailyTokensSnapshotEntity", b =>
                {
                    b.Property<string>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("date");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp");

                    b.Property<string>("TotalBurnedTokens")
                        .IsRequired()
                        .HasColumnName("total_burned_tokens");

                    b.Property<string>("TotalEarnedTokens")
                        .IsRequired()
                        .HasColumnName("total_earned_tokens");

                    b.Property<string>("TotalTokens")
                        .IsRequired()
                        .HasColumnName("total_tokens");

                    b.Property<string>("TotalTokensInCustomersWallets")
                        .IsRequired()
                        .HasColumnName("total_tokens_in_customers_wallets");

                    b.HasKey("Date");

                    b.ToTable("daily_tokens_snapshot");
                });

            modelBuilder.Entity("Lykke.Job.TokensStatistics.MsSqlRepositories.Entities.LastKnownStatsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastBurnedAmount")
                        .IsRequired()
                        .HasColumnName("last_burned_amount");

                    b.Property<string>("LastEarnedAmount")
                        .IsRequired()
                        .HasColumnName("last_earned_amount");

                    b.Property<string>("LastTotalAmount")
                        .IsRequired()
                        .HasColumnName("last_total_amount");

                    b.Property<string>("LastTotalTokensInCustomersWallets")
                        .IsRequired()
                        .HasColumnName("last_total_tokens_in_customers_wallets");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("last_token_total_amount");
                });
#pragma warning restore 612, 618
        }
    }
}
